### ISSUE TITLE
拜托分享sniper使用envoy的实践

### ISSUE THREAD

**Issue by flazx** [bilibili/sniper#12]
请问sniper在部署的时候如何使用envoy？是不是所有的http访问都先经过envoy，由envoy中转。能否分享一下sniper使用envoy的实践经验。由于envoy的文章很少，根据thought.md中的描述
> 对于 redis 和 http 服务，我们用的是 [envoy](https://www.envoyproxy.io/)。
拜托分享一下envoy的实践。

**Comment by lvht** [comment]
我抽空写篇文章

**Comment by flazx** [comment]
@lvht 大侠，十分关注您的大作哈~~

**Comment by lvht** [comment]
https://zhuanlan.zhihu.com/p/87441584
