### ISSUE TITLE
sniper中dao的model和proto自动生成的model如何映射？

### ISSUE THREAD

**Issue by flazx** [bilibili/sniper#13]
在使用过程中，发觉model不太好处理，我准备用的是<http://gorm.io>。目前方案有两种：
1. 在dao中创建orm的model，然后和pb生成model做mapping，可以采用自动生成的[orm model](https://github.com/infobloxopen/protoc-gen-gorm)。
2. 直接采用pb生成model，但需要做protoc的custom tag 。
请问你们在实践过程中是怎么处理的？

**Comment by lvht** [comment]
这个事情我已经作过[说明](https://github.com/bilibili/sniper/blob/master/thought.md#%E5%85%B3%E4%BA%8E-orm)，简单说就是不推荐使用 ORM。我所在的部门在实践中也没有使用 ORM。DAO 层是数据访问层，这里不光是访问 DB，访问缓存、调用其他接口等逻辑都应该放到这一层。这一层我们都是手写的。

**Comment by flazx** [comment]
日后我们使用一下，有问题再咨询您！
