### ISSUE TITLE
脚手架使用单独入口之后出现问题

### ISSUE THREAD

**Issue by flyqieqq** [bilibili/sniper#14]
安装所需扩展、执行`git clone https://github.com/bilibili/sniper.git` .、执行`go run cmd/sniper/main.go rpc --service=foo`均无报错.
但执行`go run main.go server --port=8080`时出错
`build command-line-arguments: cannot load sniper/cmd/falsework: malformed module path "sniper/cmd/falsework": missing dot in first path element`
删除掉main.go的falsework内容后重新执行，出错改为
```
# sniper/cmd/server
cmd/server/http.go:28:33: cannot use hooks (type *"github.com/bilibili/twirp".ServerHooks) as type *"github.com/twitchtv/twirp".ServerHooks in argument to foo_v1.NewFooServer
cmd/server/main.go:137:9: too many arguments in call to initMux
	have (*http.ServeMux, bool)
	want (*http.ServeMux)
```
 请问如何解决？望回复，谢谢

**Comment by flazx** [comment]
falsework去除就可以了，不要引入这个~~

**Comment by flyqieqq** [comment]
> falsework去除就可以了，不要引入这个~~

好的，main.go去除了falsework，请问还需要去除其他地方的吗？

**Comment by lvht** [comment]
之前 falsework 是项目代码的一部分。如果生成的代码有问题会导致编译失败，进而 falsework 子命令也无法使用。现在移除了 falsework 子命令，引入了独立的 sniper 命令来解决这个问题。

**Comment by eifrigmn** [comment]
@flyqieqq 提到的另一个问题貌似还会复现，执行如下命令：
```Go
go run cmd/sniper/main.go rpc --service=foo
go run main.go server --port=8080
```
提示：
![image](https://user-images.githubusercontent.com/14011140/72142079-eb2b8980-33ce-11ea-977c-c98d3353b3d4.png)
是不是要把`cmd/server/main.go`中的
```Go
initMux(mux, isInternal)
```
改为：
```Go
initMux(mux)
```

**Comment by lvht** [comment]
需要把`initMux(mux)`改为`initMux(mux, isInternal)`，可能你的`main.go`是之前生成的。

**Comment by eifrigmn** [comment]
好的，感谢，那我再试一下

**Comment by yigger** [comment]
> 需要把`initMux(mux)`改为`initMux(mux, isInternal)`，可能你的`main.go`是之前生成的。

应该是 `initMux(mux, isInternal)` 改为 `initMux(mux)` 吧？  我看 master 调用处传了两个参数，实际上 `cmd/server/http.go` 的 initMux 方法只接收一个参数
