### ISSUE TITLE
实践中dao层如何复用？

### ISSUE THREAD

**Issue by flazx** [bilibili/sniper#15]
我们在使用sniper的过程中，dao层的复用拿捏不太准，例如：有两个服务
--shopAdmin（商城后端服务接口）
    -- shopAdminDao
--shopHome（商城前端服务接口）
   --shopHomeDao
在dao层有很多方法可以复用（例如：获取商品详情），这个应当通过[内部服务service的接口]去调用，还是dao层直接通过代码依赖来调用来实现代码的复用呢？那种调用方式更合理呢？

**Comment by lvht** [comment]
我们这边认为 dao 层跟 service 层不需要一一对应。对于商品，你应该设一个单独的 dao，比如叫 commodityDao，服务 shopAdmin 和 shopHome 都应该调用同一个 commodityDao，不同的业务逻辑都组织到 service 层，相同的逻辑下沉到 dao 层。

service 跟 dao 层是多对多的，一个服务可以调多个 dao，一个 dao 也可以让不同的服务调用。

**Comment by flazx** [comment]
非常感谢您的答复~~
