### ISSUE TITLE
sniper 跟 kratos 的关系是？

### ISSUE THREAD

**Issue by yuanfeng0905** [bilibili/sniper#17]
B站前有 kratos 后有 sniper ，如何选型呢？

**Comment by lvht** [comment]
kratos 功能比较多，朝着大而全方向演进。sniper 是 b 站漫画部门在用的框架，功能很少，代码也很少。与其说 sniper 是一个框架，不如说是**一种推荐的开发约定，更多的是为大家提供一种设计参考**。当然了，也欢迎大家直接使用。

如何选型这个问题很容易。

你可以试着阅读 sniper 的 README 文件，并将所有文件内链接的文件（其实不多）都看一遍。如果你看完了，你就能够得出是否选用 sniper 的判断。如果你不愿意读，那就选 kratos :smile:
