### ISSUE TITLE
Cannot use 'loginHooks' (type *"github.com/bilibili/twirp".ServerHooks) as type *"github.com/twitchtv/twirp".ServerHooks 

### ISSUE THREAD

**Issue by learninto** [bilibili/sniper#18]
路径：cmd/server/http.go  

错误信息：Cannot use 'loginHooks' (type *"github.com/bilibili/twirp".ServerHooks) as type *"github.com/twitchtv/twirp".ServerHooks 

如图：
![image](https://user-images.githubusercontent.com/14171158/78877249-22b7d980-7a83-11ea-86da-eb45e8365531.png)

**Comment by lvht** [comment]
是不是引错包了。 sniper 依赖的是 github.com/bilibili/twirp 不是 github.com/twitchtv/twirp

**Comment by learninto** [comment]
使用go run cmd/sniper/main.go rpc生成的代码，cmd/server/http.go 中 引用的是 "github.com/bilibili/twirp"，所以包没有引用错

**Comment by lvht** [comment]
请使用这个 [protoc-gen-twirp](https://github.com/bilibili/twirp/tree/master/protoc-gen-twirp)，文档里已经有说明了。你应该用的是原版 protoc-gen-twirp
