### ISSUE TITLE
关于sniper的各层版本命名问题

### ISSUE THREAD

**Issue by flazx** [bilibili/sniper#23]
默认rpc下会生成版本v1，例如 app/v1/service.proto
对应的server会生成 --> appserver1
请问是不是应当对应的创建：   rpc(app/v1/service.proto) --> server(appserver1)-->service(appservice1) --> dao(appdao1)

**Comment by lvht** [comment]
版本号只针对rpc和server，其他部分不对外暴露，不需要使用版本号。

**Comment by flazx** [comment]
收到，谢谢
