### ISSUE TITLE
如何更好的区分内外部服务？

### ISSUE THREAD

**Issue by hard88** [bilibili/sniper#27]
1. 因为业务需要，想在windows起一套内部服务，但是想到编译的时候会因为一些windows的包或者linux的包无法编译。
想请问一下如何较好的解决这个问题？

2. 如果外部服务调用内部服务的话，是直接用tiwrp生成的client来请求还是写http请求？这个请求是否应该是在外部服务的dao层？

**Comment by lvht** [comment]
- 我们这边从开发到生产都没有用 windows 的，实在不好支持。有一个办法，你可以在 linux 开发，编译的时候指定 GOOS=windows，会构建 win 平台下的 exe。
- 服务相互调用建议走 twirp 的额户端。相关代码应该组织到外部服务的 dao 层。

更多信息可以加群讨论
![image](https://user-images.githubusercontent.com/2030591/89879927-353f4c80-dbf6-11ea-99b1-046678c5cbec.png)
