### ISSUE TITLE
【问题】为什么不在封装 db/mc/redis 支持，你们团队还在用这套 db/mc/redis? 不在支持后你们选择了那款db库

### ISSUE THREAD

**Issue by learninto** [bilibili/sniper#29]

**Comment by lvht** [comment]
不支持的意思是不默认集成~我们团队内部一直使用以下组件：

- https://github.com/bilibili/memcache
- https://github.com/bilibili/redis

但是这两个库主要为团队内部服务，够用就好，不一定适应其他的团队。我们内部也没有引入 orm，这个也很有争议。所以，就不在 sniper 项目提供默认集成了。这样，大家可以根据自己的实际情况选用合适的组件。

之前删除的 `util/mc` `util/db` 和 `util/redis` 都是满足部门内部需求的最小封装。尤其是 `util/redis`，仅支持一小部分 redis 的功能~把这一部分开放出来感觉不太好，我们内部又不想把这个个组件做的很臃肿，所以还是考虑不集成了。

我们有一个小群，欢迎加入讨论
![image](https://user-images.githubusercontent.com/2030591/90467866-cc048f80-e147-11ea-8eb6-cb62fb269629.png)

**Comment by learninto** [comment]
感谢回复的这么及时：

1. 我觉得你们的db组件做的挺好的。我也基于你们做的这个框架做了一些扩充，db中增加了 构建：create、update、query 三个方法。

2. redis、memcache 够用就好不需要特别复杂。

3. 有考虑在框架层增加限流？

**Comment by lvht** [comment]
其实不打算做。限流这一类服务治理的工作还是让类似 envoy 这类的专业组件来做比较好
不然，每种语言、每个框架都做一套，有点浪费，还不专业
