### ISSUE TITLE
readme 中的 '实现接口' 连接不对

### ISSUE THREAD

**Issue by chanchancl** [bilibili/sniper#38]
目前指向这里 https://github.com/bilibili/sniper/blob/master/server/README.md

显示 404 not found

看目前的结构，应该改成  /service/README.md

**Comment by lvht** [comment]
这个链接是历史原因导致的。

最早，我们是 rpc 跟 server 分开的。后来觉得 server 层不应该有太多逻辑，主要就是实现 rpc 接口并调用 service 层方法。所以就把 server 层跟 rpc 层合并到了一起。

但是，因为我们在早期 service 层有大量的代码直接依赖 rpc 层。如果合并 rpc 层跟 server 层，就会产生 rpc 导 service、service 导 rpc 这样的循环依赖。现有的代码有没法完全重写，所以我们内部还是继续使用 server 层。

**Comment by chanchancl** [comment]
如果是由于内外部引起的问题，那就没事了
多谢解答
