### ISSUE TITLE
请教一个该项目本身的问题

### ISSUE THREAD

**Issue by mrFranklin** [bilibili/sniper#6]
据我所知，b站已有一套开源的go微服务框架kratos，里面的功能也比较完备。
请问，为何不使用kratos这套框架，而要重新造个“轮子”呢？
期待答复

**Comment by lvht** [comment]
你这是**引战帖**呀~

首先，你需阅读《[sniper 的前世今生](https://github.com/bilibili/sniper/blob/master/thought.md)》，了解 sniper 的设计背景。然后，你还得根据 [README](https://github.com/bilibili/sniper/blob/master/README.md) 完成一个 demo。最后，你还得使用 kratos 完成一个 demo。到此，你自己才会有一个直观的感受。

sniper 功能太少，少到你用不了一个下午就能完全吃透。所以，sniper 可能都算不上一个框架，而是**一种思路**，是**一个原型**。你可以对 sniper 做任何改造，你甚至还能在完全消化 sniper 的基础上设计自己的框架。

最后说一下服务治理的问题。kratos 造了很多服务治理相关的轮子。我们认为，这些功能应该由 [Envoy](https://www.envoyproxy.io/) 等中间件完成（我们也在生产环境引入了 Envoy）。不然只有两种结果，一是每种语言各造一套，一是强制所有人都用 Go 语言。这都不是我们想要的结果。

**Comment by lvht** [comment]
还有一点。b站在有个大轮子的情况下还允许你造个小轮子，这样的氛围你动不动心呢？
